### ISSUE TITLE
Feature request: Change position of hero image

### ISSUE THREAD

**Issue by tensider** [Lavve/MMM-MagicSuperHero#1]
Really fun module, but I've got it living in the lower right corner of my MM and it would be great to have a config setting that shifts the hero image to the side of the information block. Thanks for your work!

**Comment by Lavve** [comment]
Hi @tensider, and thank you for your suggestion!
I've now added the possibility to change the position of the super hero image.

**Comment by tensider** [comment]
That's wonderful! Thank you so much for enabling the functionality so
quickly :)
